version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always

  portainer_agent:
    image: portainer/agent:2.19.1
    container_name: portainer_agent
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host # If you want to use the host management features of the Portainer Agent
    restart: always

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
      - PLEX_CLAIM=CLAIMCODE # Get claim code: https://www.plex.tv/claim/
      - VERSION=docker
      - NVIDIA_VISIBLE_DEVICES=all # To passthrough GPU to container
    volumes:
      - plex_config:/config
      - /mnt/media/movies:/Movies
      - /mnt/media/television:/Television
      - /mnt/media/music:/Music
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # If Intel Quick Sync is enabled
      - /dev/dri/card0:/dev/dri/card0 # If Intel Quick Sync is enabled
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - TZ=America/Vancouver
      - WATCHTOWER_CLEANUP=true # Removes old image
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  portainer_data:
  plex_config:
